# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nick's Last Weeks At LighthouseLabs
email: cnicholasjordan@gmail.com
description: 
  This is a blog written by Nick Jordan. It will cover his last few weeks at Lighthouse Labs in 
  Vancouver, BC as well as his subsequent learning and projects as he pursues a career as a junior
  web developer. In addition to development, Nick enjoys all sports (especially Houston teams), craft 
  beverages and well written songs.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: nickjordanhello
github_username:  clementnicholas

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/blog/page:num/"
