# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: I Learn So Much. And Still I Know Nothing.
email: cnicholasjordan@gmail.com
description: Nick Jordan is a graduate of Vanderbilt University. After spending some years in Nashville as a songwriter/film crew monkey/restaurant worker/general hooligan, he attended the Lighthouse Labs Web Development Bootcamp in Vancouver, BC. He has since relocated to the Bay Area. Among other things, Nick enjoys new technologies, Houston sports, being outside, craft beverages and well written songs. He is a self-proclaimed queso connouisseur.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: nickjordanhello
github_username:  clementnicholas

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/blog/page:num/"
